AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 100
            nullable: true
        lastName:
            type: string
            length: 100
            nullable: true
        createdOn:
            type: datetime
    oneToMany:
        posts:
            targetEntity: AppBundle\Entity\Post
            mappedBy: user
        messagesSent:
            targetEntity: AppBundle\Entity\Message
            mappedBy: sender
        messagesReceived:
            targetEntity: AppBundle\Entity\Message
            mappedBy: receiver